<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="10.0.1" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.9.0" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="4.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Deda.Core\Deda.Core.csproj" />
    <ProjectReference Include="..\..\src\Deda.Triggers.Prometheus\Deda.Triggers.Prometheus.csproj" />
    <ProjectReference Include="..\..\src\Deda.Triggers.Http\Deda.Triggers.Http.csproj" />
    <ProjectReference Include="..\..\src\Deda.Triggers.RabbitMq\Deda.Triggers.RabbitMq.csproj" />
    <ProjectReference Include="..\..\src\Deda.Credentials\Deda.Credentials.csproj" />
    <ProjectReference Include="..\..\src\Deda.Triggers.Ci\Deda.Triggers.Ci.csproj" />
  </ItemGroup>

</Project>
