<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-Deda.Host-c2b64d2e-b13d-4bd0-8ad5-5f499e272010</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerfileContext>..\..</DockerfileContext>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Deda.Core\Deda.Core.csproj" />
    <ProjectReference Include="..\Deda.Controller\Deda.Controller.csproj" />
    <ProjectReference Include="..\Deda.Swarm\Deda.Swarm.csproj" />
    <ProjectReference Include="..\Deda.Config.Labels\Deda.Config.Labels.csproj" />
    <ProjectReference Include="..\Deda.Triggers.Abstractions\Deda.Triggers.Abstractions.csproj" />
    <ProjectReference Include="..\Deda.Triggers.Prometheus\Deda.Triggers.Prometheus.csproj" />
    <ProjectReference Include="..\Deda.Triggers.RabbitMq\Deda.Triggers.RabbitMq.csproj" />
    <ProjectReference Include="..\Deda.Updates\Deda.Updates.csproj" />
    <ProjectReference Include="..\Deda.HA\Deda.HA.csproj" />
    <ProjectReference Include="..\Deda.Observability\Deda.Observability.csproj" />
    <ProjectReference Include="..\Deda.Policies\Deda.Policies.csproj" />
  </ItemGroup>
</Project>
